project:
  type: website
  output-dir: public
  render: 
    - "*.qmd"
    - "!04_data_analysis/992_scripts_from_frank"

#toc: true
#number-sections: true
#bibliography: references.bib

execute:
  freeze: auto
  warning: false
  message: false
    
website:
  title: "Blood brain barrier in AD"
  navbar:
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Data analysis"
        file: 06_dissemination/03_website/01_data-analysis.qmd
        
  sidebar:
    - title: "Data analysis"
      style: "docked"
      background: light
      contents:
        - 06_dissemination/03_website/01_data-analysis.qmd
        - 04_data_analysis/001_snrnaseq_analysis/01_fastqc.qmd
        - 04_data_analysis/001_snrnaseq_analysis/02_multiqc.qmd
        - 04_data_analysis/001_snrnaseq_analysis/03_generate_cellranger_reference.qmd

  
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    number-sections: true
    code-fold: true
    code-tools: true
    code-link: true
    embed-resources: false