project:
  type: website
  output-dir: public
  render: 
    - "*.qmd"
    - "!04_data_analysis/992_scripts_from_frank"

#toc: true
#number-sections: true
#bibliography: references.bib

execute:
  freeze: auto
  warning: false
  message: false
    
# add multiqc reports to website
resources:
  - "03_data/990_processed_data/001_snrnaseq/02_multiqc/01_set1_reads/fastqc_endo_10x_set1_reads.html"
  - "03_data/990_processed_data/001_snrnaseq/02_multiqc/01_set1_reads/fastqc_endo_10x_set1_reads_data"
  - "03_data/990_processed_data/001_snrnaseq/02_multiqc/02_set2_reads/fastqc_endo_10x_set2_reads.html"
  - "03_data/990_processed_data/001_snrnaseq/02_multiqc/02_set2_reads/fastqc_endo_10x_set2_reads_data"
  - "03_data/990_processed_data/001_snrnaseq/02_multiqc/03_set3_reads/fastqc_endo_10x_set3_reads.html"
  - "03_data/990_processed_data/001_snrnaseq/02_multiqc/02_set2_reads/fastqc_endo_10x_set3_reads_data"
  
website:
  title: "Blood brain barrier in AD"
  navbar:
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Data analysis"
        file: 06_dissemination/03_website/01_data-analysis.qmd
        
  sidebar:
    - title: "Data analysis"
      style: "docked"
      background: light
      contents:
        - 06_dissemination/03_website/01_data-analysis.qmd
        - 04_data_analysis/001_snrnaseq_analysis/01_fastqc.qmd
        - 04_data_analysis/001_snrnaseq_analysis/02_multiqc.qmd
        - 04_data_analysis/001_snrnaseq_analysis/03_generate_cellranger_reference.qmd

  
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    number-sections: true
    code-fold: show
    code-tools: true
    code-link: true
    embed-resources: false